cask_args appdir: "/Applications"

tap "caius/es101"
tap "caskroom/cask"
tap "homebrew/versions"

brew "zsh"
brew "zsh-syntax-highlighting"
brew "git"
brew "gnutls"

cask "textmate"
cask "launchbar"

brew "openssl"
brew "libyaml"
brew "libxml2"
brew "libxslt"
brew "libiconv"
brew "autoconf"
brew "automake"
brew "chruby"
brew "ruby-install"

brew "apple-gcc42"
brew "blueutil"
brew "coreutils"
brew "csshx"
brew "dnsmasq"
brew "dos2unix"
brew "gnu-sed"
brew "gnu-time"
brew "gnupg"
brew "jq"
brew "links"
brew "lynx"
brew "proctools"
brew "psgrep"
brew "pstree"
brew "pwgen"
brew "python"
brew "renameutils"
brew "shellcheck"
brew "the_silver_searcher"
brew "tree"
brew "wakeonlan"
brew "watch"
brew "wdiff"
brew "wget"
brew "xz"
brew "youtube-dl"

brew "imagemagick"
brew "optipng"
brew "pngcrush"
brew "elasticsearch15"
brew "mariadb100"
brew "v8-315"
brew "tinyproxy"
brew "s3cmd"
brew "rabbitmq"
brew "qt"

cask "blockblockius"
cask "spectacle"
cask "menumeters"
cask "cyberduck"
cask "dropbox"
cask "flux"
cask "gitx"
cask "google_drive"
cask "macdown"
cask "mou"
cask "screenhero"
cask "things"
cask "vmware"
cask "viscosity"
